export enum IndustryType {
  'Agriculture' = 'Agriculture',
  'Cloud-based solutions or services' = 'Cloud-based solutions or services',
  'Consulting' = 'Consulting',
  'Data and analytics' = 'Data and analytics',
  'Education and training' = 'Education and training',
  'Energy or utilities' = 'Energy or utilities',
  'Financial and banking' = 'Financial and banking',
  'Government or public administration' = 'Government or public administration',
  'Health care or social services' = 'Health care or social services',
  'Information technology' = 'Information technology',
  'Internet' = 'Internet',
  'Manufacturing' = 'Manufacturing',
  'Marketing' = 'Marketing',
  'Media, advertising, publishing, or entertainment' = 'Media, advertising, publishing, or entertainment',
  'Nonprofit' = 'Nonprofit',
  'Real estate' = 'Real estate',
  'Research - academic or scientific' = 'Research - academic or scientific',
  'Retail or ecommerce' = 'Retail or ecommerce',
  'Security' = 'Security',
  'Software as a service (saas) development' = 'Software as a service (saas) development',
  'Software development - other' = 'Software development - other',
  'Telecommunications' = 'Telecommunications',
  'Transportation' = 'Transportation',
  'Travel' = 'Travel',
  'Web development or design' = 'Web development or design',
}
